### ISSUE TITLE
Localhost Error: failed to compile

### ISSUE THREAD

**Issue by PhiPhiPhi** [fangpenlin/avataaars-generator#19]
(219,26): error TS2339: Property 'outerHTML' does not exist on type 'Element | Text'.
  Property 'outerHTML' does not exist on type 'Text'.

**Comment by maribossi** [comment]
Hi, I am having the same issue, did you manage to solve this?

**Comment by PhiPhiPhi** [comment]
Hello, yes I solved this by using the control: `if (svgNode instanceof HTMLDivElement)` in the onDownloadPNG and onDownloadSVG functions in order to force the svgNode to not be null or a text. Hope this helps.
