### ISSUE TITLE
BeardMagestic is not showing up when image is loaded with SVG <img> markup api code

### ISSUE THREAD

**Issue by vahorarahil10github** [fangpenlin/avataaars-generator#22]
Dear Lin,

To reproduce this issue, generate any avatar with { facialHairType: BeardMagestic } query, copy the given SVG <img> markup api code and load it in a browser. BeardMagestic facial hair will not show up.

Thanks for making this project open source! It is very creative and has amazing use cases!

Rahil

**Comment by Benmidi** [comment]
I noticed this too with the react component; was able to use BeardMajestic instead :)
