### ISSUE TITLE
I am writing a native Angular application for this as well

### ISSUE THREAD

**Issue by BaileyMillerSSI** [fangpenlin/avataaars-generator#26]
Using the React code as a baseline I am writing a version of this code that uses everything Angular rather than requesting an image from the website. 

I have currently added the ability to create an avatar and custom the body color, and the shirt type.

As I progress in writing this Angular module I will update this issue with a github repo for anyone that is looking to create an Angular app with this.

**Comment by ttariq7** [comment]
Nice. I'd be interested in using this. Let me know if you need any help

**Comment by BaileyMillerSSI** [comment]
I am essentially do what the react components do and add svg files together to generate a complete svg tag

**Comment by shivam1410** [comment]
@BaileyMillerSSI  @fangpenlin  @gkoberger  @weisisheng I have also tried to cloned this website for creating avtaars in native angular and angular material, and mainly for open project work, should i keep working and  deploy it or It can be a copyright issue to do so. I must add that this is just for project work only.

**Comment by JacobDel** [comment]
Any updates?
