### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by davidecampello** [fangpenlin/avataaars-generator#54]
Hello thanks for this amazing project! Unfortunatly today the app is down...
Can we do something to help?
Thanks

**Comment by thangdjw** [comment]
@fangpenlin i have the same problem. do you have any idea about this bug ?

**Comment by MercedesElliot** [comment]
>
> *thank you*


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
