### ISSUE TITLE
Suggestion: Please update the about section with the project url

### ISSUE THREAD

**Issue by akhilmhdh** [fangpenlin/avataaars-generator#82]
Hey there, awesome project. Can you please put the hosted [url](https://getavataaars.com) of the project  to the about section. As people used to github tends to look to the about section for project links more.

![Screenshot 2021-09-25 at 8 23 53 PM](https://user-images.githubusercontent.com/31166322/134775843-05b00f98-8b55-4be3-a6ed-3aec228382b5.png)

**Comment by fangpenlin** [comment]
Hi, thanks for the suggestion. just added the URL
